---
title: "New maps show how neighbourhood deprivation in England can be visualised to avoid misleading the public"
author: "Samuel Langton"
output: word_document
---

In September of this year, the latest neighbourhood deprivation statistics were released by The Ministry of Housing, Communities and Local Government. Widely reported by the [BBC](https://www.bbc.co.uk/news/uk-england-49812519), and [The Guardian](https://www.theguardian.com/society/2019/sep/26/wealthy-incomers-changing-profile-of-londons-most-deprived-areas), amongst others, the figures reignited long-standing debates about regional inequality in England, and the [stability](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/835115/IoD2019_Statistical_Release.pdf) of neighbourhood deprivation over time.

A key method which the media and the government has used to communicate these findings has been [maps](https://imd2019.group.shef.ac.uk). It is easy to see why: maps are a visually appealing, accessible and powerful way to convey complex information to the public. However, even the most beautiful maps can introduce some degree of misrepresentation. Irregularly sized areas, and large disparities in the size of areas being visualised, can mislead readers, diverting attention away from important information. In the BBC's [map](https://www.bbc.co.uk/news/uk-england-49812519) of deprivation across Local Authorities, for instance, sparsely populated rural areas dominate a disproportionately large amount of the visual, with urban areas like London, containing millions of people, rendered almost invisible.

[Recent research](https://osf.io/preprints/socarxiv/t6agd/) has shown that people can interpret information inaccurately when viewing maps which suffer from such shortcomings. Instead, alternative visualisation techniques can be used which better convey the underlying data. For instance, [cartograms](https://www.tandfonline.com/doi/full/10.1111/j.1467-8306.2004.09401004.x?casa_token=PCQuJ1wUlkoAAAAA:m8aWeOyHWcKv-iL8T1-bXlcunBnzZV2lkAz3-gYAxUtgRCihbAYOIWz8-HJFvSOO8WP4W25tLA) deliberately distort the raw geography by scaling areas according to a specified variable, such as resident population size. [Dorling cartograms](https://www.arcgis.com/home/item.html?id=b686a7679cb747e9825d1d1bb6b26046) take this one step further, by scaling areas according to a specified variable, but also representing each as uniform shapes, such as circles. Other methods achieve uniformity in both size and shape. [Hexograms](http://gisruk.org/ProceedingsGISRUK2018/GISRUK2018_Contribution_023.pdf) and [geogrids](https://github.com/jbaileyh/geogrid) transform the original boundaries to hexagons or squares, which are equally sized, but still aim to preserve the original topology.

Visualising neighbourhood deprivation in England represents a significant [challenge](https://theconversation.com/these-maps-show-how-tricky-it-is-to-measure-inequality-in-local-areas-across-england-109143) when creating maps. This is because the government's definition of 'neighbourhood' is a [Lower Super Output Area](https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography). These areas are designed to be uniform by population, containing around 1500 residents. A result of this is that highly deprived neighbourhoods, which tend to be densely populated, are quite small when visualised, making them less visible. By contrast, wealthier suburban areas, which are often less densely populated and therefore much larger, dominate the map. Consequently, readers might draw inaccurate conclusions about the level of deprivation in any given area. Using [Dorling cartograms](https://www.arcgis.com/home/item.html?id=b686a7679cb747e9825d1d1bb6b26046), scaled by resident population, and regular hexagonal [geogrids](https://github.com/jbaileyh/geogrid), one can minimise the misrepresentation that might occur.

Take the example below of Blackpool, which was [ranked](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/835115/IoD2019_Statistical_Release.pdf) the most deprived Local Authority in England. Around 42% of neighbourhoods in Blackpool are in the top 10% most deprived in England (the 'first decile') and yet these neighbourhoods only make up around 29% of Blackpool in terms of area. Using a Dorling cartogram scaled by resident population size, neighbourhoods in the first decile constitute 41% of the map in terms of area, and the larger, less deprived neighbourhoods (in light blue) have been shrunk accordingly, becoming less dominant. With a regular hexagonal geogrid, the proportion of the map consisting of first decile neighbourhoods mimics the underlying data, at 42%. Variation in the sizes and shapes of Blackpool neighbourhoods no longer divert attention or mislead readers, and arguably, the underlying data has been conveyed more accurately than with the original map.

[Caption: Index of Multiple Deprviation deciles (2019) at Lower Super Output Area level for Blackpool using original boundaries, Dorling cartogram and geogrid. Contains OS Data \© Crown copyright 2019]

These alternative visuals have a similar impact when mapping out deprivation in Burnley and Hartepool, which were among the most deprived Local Authorities. Both areas are characterised by many small, highly concentrated neighbourhoods in the first decile (most deprived), surrounded by much larger, and much wealthier suburbs. At a glance, the pervasiveness of deprivation in these Local Authorities is likely to be drastically understated using the original boundaries. Using the Dorling cartogram, again scaled by population, and the hexagonal geogrids, the issue can be somewhat rectified. Interestingly, however, this comes at a cost: the geogrid in particular has distorted the topology of the original data, pushing some neighbourhoods apart, and forcing some together. Making these transformations should be done with care, and decisions guided by the aims of the research and the target audience.

[Caption: Index of Multiple Deprviation deciles (2019) at Lower Super Output Area level for Burnley and Hartepool using original boundaries, Dorling cartogram and geogrid. Contains OS Data \© Crown copyright 2019]

Birmingham and Manchester, ranked within the top ten most deprived Local Authorities, represent a different challenge (see below). With much larger populations, and many more neighbourhoods to visualise, readers are faced with an overwhelming amount of information when viewing the original map. Once again, both the Dorling cartogram and the geogrid perform admirably when seeking to minimise the impact of large areas, especially in the north of Birmingham. Using regular shapes also makes the maps more accessible, and it is arguably much easier to deduce information from the Dorling cartogram and geogrid compared to the original. In doing so, the original topology is maintained well, with minimal distortion to the location and patterning of neighbourhoods.

[Caption: Index of Multiple Deprviation deciles (2019) at Lower Super Output Area level for Manchester and Birmingham using original boundaries, Dorling cartogram and geogrid. Contains OS Data \© Crown copyright 2019]

There is no 'rule of thumb' when considering how best to create beautiful but accurate geographic visualisations. In this case, using the latest neighbourhood deprivation data in England, mapping out the original boundaries can clearly introduce some degree of misrepresentation. This warrants some concern when reporting to the public, given the social and political importance of such data. With [recent research](https://osf.io/preprints/socarxiv/t6agd/) in mind, these demonstrations hopefully highlight the value of alternative, non-traditional cartographic techniques, and the need for the media and the government to think outside the box when it comes to reporting geographic information.







